// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-FddAhNGzsdX_2RY9JggX-P9pK9rgeVU',
    appId: '1:185920003877:web:9e965e02691ac92989c4cc',
    messagingSenderId: '185920003877',
    projectId: 'social-trip-3b4c4',
    authDomain: 'social-trip-3b4c4.firebaseapp.com',
    storageBucket: 'social-trip-3b4c4.appspot.com',
    measurementId: 'G-XZE19H5FV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUtT9mqTYasRjlaDgpSAtDTZ6c9X4phI',
    appId: '1:185920003877:android:cf7b562cec24670389c4cc',
    messagingSenderId: '185920003877',
    projectId: 'social-trip-3b4c4',
    storageBucket: 'social-trip-3b4c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2X1jRqie2TR777XFU5Z0dRHRORRenMl8',
    appId: '1:185920003877:ios:a1eb0df4ca0a4e0f89c4cc',
    messagingSenderId: '185920003877',
    projectId: 'social-trip-3b4c4',
    storageBucket: 'social-trip-3b4c4.appspot.com',
    iosClientId: '185920003877-a1hd4rf9kcu4fr6eb0qfa00mtkcoksuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.turismoapp',
  );
}
